version: '3'  #docker-compose file version
services:
  scm:    
    image: scmmanager/scm-manager:2.12.0
    container_name: scmmanager
    ports:    
    - 8080:8080    # if the ssh plugin is used    
    - 2222:2222 
    volumes:
    - ./docker/scm_home:/var/lib/scm #user of folder shall be same as java user    
